// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CryptoExchangeService_GetPrice_FullMethodName = "/pb.CryptoExchangeService/GetPrice"
)

// CryptoExchangeServiceClient is the client API for CryptoExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoExchangeServiceClient interface {
	GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*GetPriceResponse, error)
}

type cryptoExchangeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoExchangeServiceClient(cc grpc.ClientConnInterface) CryptoExchangeServiceClient {
	return &cryptoExchangeServiceClient{cc}
}

func (c *cryptoExchangeServiceClient) GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*GetPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPriceResponse)
	err := c.cc.Invoke(ctx, CryptoExchangeService_GetPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoExchangeServiceServer is the server API for CryptoExchangeService service.
// All implementations must embed UnimplementedCryptoExchangeServiceServer
// for forward compatibility
type CryptoExchangeServiceServer interface {
	GetPrice(context.Context, *GetPriceRequest) (*GetPriceResponse, error)
	mustEmbedUnimplementedCryptoExchangeServiceServer()
}

// UnimplementedCryptoExchangeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCryptoExchangeServiceServer struct {
}

func (UnimplementedCryptoExchangeServiceServer) GetPrice(context.Context, *GetPriceRequest) (*GetPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedCryptoExchangeServiceServer) mustEmbedUnimplementedCryptoExchangeServiceServer() {}

// UnsafeCryptoExchangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoExchangeServiceServer will
// result in compilation errors.
type UnsafeCryptoExchangeServiceServer interface {
	mustEmbedUnimplementedCryptoExchangeServiceServer()
}

func RegisterCryptoExchangeServiceServer(s grpc.ServiceRegistrar, srv CryptoExchangeServiceServer) {
	s.RegisterService(&CryptoExchangeService_ServiceDesc, srv)
}

func _CryptoExchangeService_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoExchangeServiceServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoExchangeService_GetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoExchangeServiceServer).GetPrice(ctx, req.(*GetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoExchangeService_ServiceDesc is the grpc.ServiceDesc for CryptoExchangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoExchangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CryptoExchangeService",
	HandlerType: (*CryptoExchangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _CryptoExchangeService_GetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
