// Code generated by mockery v2.46.1. DO NOT EDIT.

package mock

import (
	models "garantex/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// DoRequest provides a mock function with given fields:
func (_m *Client) DoRequest() (*models.PriceDepth, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DoRequest")
	}

	var r0 *models.PriceDepth
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.PriceDepth, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.PriceDepth); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PriceDepth)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
